# PostgreSQL only for testing
services:
  postgres:
    image: postgres:15-alpine
    container_name: esport-postgres-test
    environment:
      POSTGRES_DB: esport_coach
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d esport_coach"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_test_data:
    driver: local

networks:
  default:
    name: postgres-test-network