# Development Extension File - DEPRECATED
# ===============================================
# 
# ⚠️  THIS FILE IS NO LONGER NEEDED! ⚠️
#
# All services have been moved to the main docker-compose.yml file.
# 
# INSTEAD OF THIS FILE, USE:
#
# 1. Main development setup:
#    cd /app
#    docker-compose up -d
#
# 2. Enhanced startup script:
#    ./scripts/start-dev.sh
#
# 3. Check status:
#    docker-compose ps
#
# ===============================================
#
# This file was used when services were missing from the main
# docker-compose.yml file. Now that all services are properly
# included in the main file, this extension is not needed.
#
# The main docker-compose.yml now includes:
# - All infrastructure services (PostgreSQL, Redis, etc.)
# - All application services (API Gateway, Auth, User, etc.)
# - All missing services (Messaging, Ratings, Search)
# - Proper networking and health checks
# - Development volume mounts
#
# ===============================================