version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - COACH_SERVICE_URL=http://coach-service:3003
      - SESSION_SERVICE_URL=http://session-service:3004
      - VIDEO_SERVICE_URL=http://video-service:3005
      - MESSAGING_SERVICE_URL=http://messaging-service:3006
      - PAYMENT_SERVICE_URL=http://payment-service:3007
      - RATINGS_SERVICE_URL=http://ratings-service:3008
      - SEARCH_SERVICE_URL=http://search-service:3009
    depends_on:
      - auth-service
      - user-service
    volumes:
      - ../services/api-gateway:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - esport-coach-network

  # Microservices
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/esport_coach
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-secret-key
    depends_on:
      - postgres
      - redis
    volumes:
      - ../services/auth-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - esport-coach-network

  user-service:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/esport_coach
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats
    volumes:
      - ../services/user-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - esport-coach-network

  coach-service:
    build:
      context: ../services/coach-service
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/esport_coach
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats
    volumes:
      - ../services/coach-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - esport-coach-network

  session-service:
    build:
      context: ../services/session-service
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/esport_coach
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats
    volumes:
      - ../services/session-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - esport-coach-network

networks:
  esport-coach-network:
    external: true